apiVersion: v1
kind: PersistentVolume
metadata:
  name: jupyter-xnat-gpfs-shared
  annotations:
    pv.kubernetes.io/provisioned-by: nfs.csi.k8s.io
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4.2
  storageClassName: nfs-csi
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: nfs-server.storage.svc.cluster.local/gpfs##jupyter
    volumeAttributes:
      server: nfs-server.storage.svc.cluster.local
      share: /gpfs
