apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: xnat-gpfs
  namespace: jupyter
spec:
  storageClassName: nfs-csi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: jupyter-xnat-gpfs-shared
