apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf-config
  namespace: mounts
data:
  telegraf.conf: |
    [agent]
      interval = "30s"
      hostname = "cvmfs-metrics"

    [[inputs.socket_listener]]
      service_address = "udp://:8092"
      data_format = "influx"

    [[outputs.prometheus_client]]
      listen = ":9001"
      metric_version = 2
