apiVersion: v1
kind: Service
metadata:
  name: cvmfs-metrics
  namespace: mounts
  labels:
    app: cvmfs-trace-parser
spec:
  selector:
    app: cvmfs-trace-parser
  ports:
  - name: metrics
    port: 9002
    targetPort: 9002
    protocol: TCP
  - name: telegraf-metrics
    port: 9001
    targetPort: 9001
    protocol: TCP
  - name: influx-udp
    port: 8092
    targetPort: 8092
    protocol: UDP
  type: ClusterIP
