apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cvmfs
  namespace: jupyter
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1  # Dummy value - actual storage from CVMFS
  storageClassName: cvmfs